### ISSUE TITLE
JOSS review by Sherwood issue 3

### ISSUE THREAD

**Issue by csherwood-usgs** [TomasBeuzen/pybeach#3]
The example notebook https://github.com/TomasBeuzen/pybeach/blob/master/example/example.ipynb
refers to pydune instead of pybeach. Unfortunately, there is also a package out there on GitLab called pydune. Installation of pybeach using pip install worked fine, and this example worked as indicated after I added the magic command `%matplotlib inline`. I notice scikit-learn is required...I already had that in my environment, but I don't think the documentation for pybeach indicates that it is required.

**Comment by TomasBeuzen** [comment]
I had originally called the package **pydune** until I found out that the name was already taken on PyPi (by a [package](https://pypi.org/project/pyDune/) that has not been updated since 2012!). I then changed the name to **pybeach**.  Based on this comment:
- I've corrected those remaining references to "pydune" in the [example notebook](https://github.com/TomasBeuzen/pybeach/blob/master/example/example.ipynb).
- I've added the notebook magic `%matplotlib inline` to the example notebook.
- I've added a section on dependencies in the [readme](https://github.com/TomasBeuzen/pybeach/blob/master/README.md#dependencies)

**Comment by kbarnhart** [comment]
Just linking this with the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1890)
